### PR TITLE
Build/naming improvements

### PR DESCRIPTION
**Pull request by kjsmita6**
- Use java17
- Remove unneeded repositories
- Rename packages/artifacts to org.firepowered.nasabot
- Organize imports across all files

### CODE REVIEW

**Comment by kjsmita6** [comment]
Bump.

**Comment by kjsmita6** [comment]
Bump?

**Review by SniperNoob95 — CHANGES_REQUESTED** [review]
As discussed we won't be transferring this to FirePowered ownership, and aren't ready to update the server to Java 17 yet. If you can pare this down just to the POM improvements and whatever restructuring you felt was appropriate that will work though. If that's too much to redo I can do that on my end.

**Comment by kjsmita6** [comment]
As discussed also the groupId doesn't dictate ownership, it is just a set of coordinates. If you are not doing org.firepowered (which I would recommend as it is made by the owner of FirePowered and hosted on FirePowered's servers using FirePowered's resources) you should at least do something to follow standard Java conventions. Including the package names.

**Comment by SniperNoob95** [comment]
Will convert to standard convention separately then.

**Pull request closed without merging**
